databases: HcPWy8b9qTkf3rrGDIKAQ6ckWbAAKtTGXH860jo38F74M5uAELwp0YhKVKdIle2rvz5zd45dX8KcUUJ+9defgHB2W5LRUGtyOawiEE4r9/Tn6is9Se2BTZ351vSwF3rPCGoNI+JpYxRv4haUabITNcrgS9ARDD5oDgq8uy9RHdq+QlgWrKrwwqfRHf/JX0R7yJQ/6do50dNKPefcm263cqfVxISnsA+uirtoDZBw3mrtudBAFR+FL+wh+yMsKKmk4n45PkEZHS2jMhMNoV18NuSWLTQkmSOdDS6M1tYeqz2sNNhPVOqPZtYdHrE/rMhg8E4dosVGHRunc8QZIEBcM9P6fwZ5SgMn8TL084ITcn7yk531UifTK+TbThaRAki3AZKbkujd3+8Ub/fteNBfLHDX8sJ/Fum+m/Lh--lsp/n8iN+pSuv/S8--PHPzAGys7ID7LzRFylboGQ==
- name: recipe_app
    user: recipe_app

services:
  - type: web
    name: recipe_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
