default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Recipe_App_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: Recipe_App_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: Recipe_App_production
  username: Recipe_App
  password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>
